apiVersion: v1
kind: Service
metadata:
  name: careermate-backend
  namespace: careermate
  labels:
    app: careermate-backend
spec:
  type: NodePort
  selector:
    app: careermate-backend
  ports:
    - name: http
      port: 18080
      targetPort: http
      nodePort: 31080
