apiVersion: v1
kind: Service
metadata:
  name: careermate-frontend
  namespace: careermate
  labels:
    app: careermate-frontend
spec:
  type: NodePort
  selector:
    app: careermate-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31000
